<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Generic\Generic.csproj" />
    <ProjectReference Include="..\MediaPlayer.Common\MediaPlayer.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LibVLCSharp" Version="3.9.4" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.21" />
    <PackageReference Include="System.ComponentModel.Composition" Version="10.0.7" />
  </ItemGroup>
</Project>
