<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Generic\Generic.csproj" />
    <ProjectReference Include="..\MediaPlayer.ViewModel\MediaPlayer.ViewModel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
    <PackageReference Include="System.ComponentModel.Composition" Version="10.0.7" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>
</Project>
